export default {
    ACTIVATE_NEW_FILM: 'activateNewFilm',
    BIND_GLOBAL_KEYS: 'bindGlobalKeys',
    LOAD_FILMS: 'loadFilms',
    LOAD_FILM: 'loadFilm',
    DELETE_FILM: 'deleteFilm',
    CLONE: 'clone',
    DELETE_ELEMENT: 'deleteElement',
    DELETE_SELECTION: 'deleteSelection',
    IMPORT: 'import',
    MASK_CONVERT: 'maskConvert',
    MOUNT_APP: 'mountApp',
    PICK_PEN: 'PICK_PEN',
    PLAY: 'play',
    RENEW_COLORS: 'renewColors',
    SAVE_FILM_AS: 'saveFilmAs',
    START_DRAW: 'startDraw',
    START_SELECT: 'startSelect',
    START_ZOOM: 'startZoom',
    TOGGLE_PLAY: 'togglePlay',
    UPDATE_FILM: 'updateFilm',
    START_CAMERA: 'startCamera',
    FILMS_LIST: 'filmsList',



    CHECK_AUTH: "checkAuth",
    CHECK_ADMIN: "checkAdmin",
    CHECK_OWNERSHIP: "checkOwnership",
    CONFIRM_SUSCRIBE: 'CONFIRM_SUSCRIBE',
    EXCEPTION: 'exception',
    GO_LOGIN: "goLogin",
    GO_HOME: 'goHome',
    GO_TO: 'goTo',
    INIT_X_REQUEST_ID: 'initCorrelationId',
    LOGIN: 'login',
    LOAD_USER: 'loadUser',
    LOGOUT: 'logout',
    SHOW_DIALOG: 'showDialog',
    SNACKBAR: 'snackbar',
    SNACKERROR: 'snackbarError',
    UPDATE_USER: "updateUser",
    USER_FROM_STORAGE: 'restoreUserFromStorage',
    USER_TO_STORAGE: 'userToStorage',
    WANT_SUSCRIBE: 'wantSuscribe',
}