export default {
    ADD_POINT: 'addPoint',
    ADD_MASK_TO_FILM: 'addMaskToFilm',
    ADD_MASK_TO_PEN: 'addMaskToPen',
    ACTIVATE_NEW_FILM: 'activateNewFilm',
    ACTIVATE_FIRST_PEN: 'activateFirstPen',
    APPLY_SIMPLIFICATION: 'applySimplification',
    ADD_ELEMENT_INSTANCE: 'addElementInstance',
    CLEAR_FILM: 'clearFilm',
    DELETE_ELEMENT: 'deleteElement',
    INSTANTIATE: 'instantiate',
    KEEP: 'keep',
    NEXT: 'next',
    PREV: 'prev',
    PAUSE: 'pause',
    PLAY: 'play',
    REWIND: 'rewind',
    SELECT_ELEMENT: 'selectElement',
    SELECT_FILM: 'selectFilm',
    SELECT_PEN: 'selectPen',
    SET_MENU_VISIBILITY: 'setMenuVisibility',
    SET_MODE: 'setMode',
    SET_SELECTION_ELEMENT: 'setSelectionElement',
    SET_SELECTION_BOX:'setSelectionBox',
    SHOW_IMPORT_DIALOG: 'showImportDialog',
    TOGGLE_MENU_VISIBILITY: 'toggleMenuVisibility',
    UNKEEP: 'unkeep',
    UNSELECT_ELEMENT: 'unselectElement',
};
