export default {
    ADD_ELEMENT: 'addElement',
    ADD_POINT: 'addPoint',
    ACTIVATE_NEW_FILM: 'activateNewFilm',
    ACTIVATE_FIRST_PEN: 'activateFirstPen',
    APPLY_SIMPLIFICATION: 'applySimplification',
    TOGGLE_MENU_VISIBILITY: 'toggleMenuVisibility',
    SET_MENU_VISIBILITY: 'setMenuVisibility',
    IMPORT: 'import',
    SHOW_IMPORT_DIALOG: 'showImportDialog',
    REWIND: 'rewind',
    PREV: 'prev',
    NEXT: 'next',
    KEEP: 'keep',
    UNKEEP: 'unkeep',
    PAUSE: 'pause',
    PLAY: 'play',
    UNSELECT: 'unselect',
    SET_MODE: 'setMode',
    CLONE: 'clone',
    CLEAR_FILM: 'clearFilm',
    DELETE_ELEMENT: 'deleteElement',
    SELECT_FILM: 'selectFilm',
    SELECT_PEN: 'selectPen',
    SET_SELECTION_ELEMENT: 'setSelectionElement',
    SET_SELECTION_BOX:'setSelectionBox',
};