export default {
    TOGGLE_MENU_VISIBILITY: 'toggleMenuVisibility',
    SET_MENU_VISIBILITY: 'setMenuVisibility',
    ACTIVATE_NEW_FILM: 'activateNewFilm',
    ACTIVATE_FIRST_PEN: 'activateFirstPen',
    REWIND: 'rewind',
    PREV: 'prev',
    NEXT: 'next',
    KEEP: 'keep',
    UNKEEP: 'unkeep',
    PAUSE: 'pause',
    PLAY: 'play',
    UNSELECT: 'unselect',
    CLONE_SELECTION: 'cloneSelection',
    CLEAR_FILM: 'clearFilm',
    DELETE_SELECTED_ELEMENT: 'deleteSelectedElement',
    APPLY_SIMPLIFICATION: 'applySimplification',
    SELECT_FILM: 'selectFilm',
    SELECT_PEN: 'selectPen',
    SET_SELECTION_ELEMENT: 'setSelectionElement',
    SET_SELECTION_BOX:'setSelectionBox',
    ADD_ELEMENT: 'addElement',
    ADD_POINT: 'addPoint'
};