export default {
    ACTIVATE_NEW_FILM: 'activateNewFilm',
    BIND_GLOBAL_KEYS: 'bindGlobalKeys',
    LOAD_FILMS: 'loadFilms',
    LOAD_FILM: 'loadFilm',
    DELETE_FILM: 'deleteFilm',
    CLONE: 'clone',
    DELETE_ELEMENT: 'deleteElement',
    DELETE_SELECTION: 'deleteSelection',
    IMPORT: 'import',
    MASK_CONVERT: 'maskConvert',
    MOUNT_APP: 'mountApp',
    PICK_PEN: 'PICK_PEN',
    PLAY: 'play',
    SAVE_FILM_AS: 'saveFilmAs',
    START_DRAW: 'startDraw',
    START_SELECT: 'startSelect',
    START_ZOOM: 'startZoom',
    TOGGLE_PLAY: 'togglePlay',
    UPDATE_FILM: 'updateFilm',
    START_CAMERA: 'startCamera'
};